kumuluzee:
  name: bikerentservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/bikerentservice
    connection-url: jdbc:postgresql://localhost:5432/cityBikeShare
    username: postgres
    password: admin
    max-pool-size: 20

  discovery:
    consul:
      agent: http://localhost:8500

  config:
    consul:
      agent: http://localhost:8500
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/bikerentservice
      http-health-check:
      - connection-url: https://github.com/CityBikeShare/BikeRentService
#      - connection-url: https://nonvalidurl.com

  metrics:
    web-instrumentation:
    - name: metrics-endpoint
      url-pattern: /sources/*
      status-codes: "200, 400, 404, 500"
    servlet:
      enabled: true